#!/bin/zsh
# Example: ./run redis

if [ "$1" = "redis" ]
then
    if [ "$2" = "db" ]
      then
        if [ "$3" -eq 0 ]
          then
            echo "Redis available databases"
            docker exec -it memseed_redis_1 redis-cli INFO | grep ^db
        else
          echo "Connected to redis db $3"
          docker exec -it memseed_redis_1 redis-cli -n "$3"
        fi
    else
      echo "Connected to redis db 0"
      docker exec -it memseed_redis_1 redis-cli
    fi
elif [ "$1" = "up" ]
then
    docker-compose -f docker-compose.noruby.yml down
    docker-compose -f docker-compose.noruby.yml up
elif [ "$1" = "testenv" ]
then
  RAILS_ENV=test bin/rake app:build parallel=false
elif [ "$1" = "specs" ]
then
    RAILS_ENV=test bin/rake app:build
    RAILS_ENV=test bundle exec rake parallel:spec
    RAILS_ENV=test bundle exec rake parallel:features
elif [ "$1" = "specs_run" ]
then
    RAILS_ENV=test bundle exec rake parallel:spec
elif [ "$1" = "features_run" ]
then
    RAILS_ENV=test bundle exec rake parallel:features
elif [ "$1" = "staging" ]
then
  ssh -t membean@pod.aws.membean.com "cd /home/membean/memseed/staging/current && bash"
  # cd works but how to invoke more???
  # bundle exec rails console staging
elif [ "$1" = "down" ]
then
  docker-compose -f docker-compose.noruby.yml down
  docker-compose -f docker-compose.noruby.yml down
else
    echo "Provide choices:"
    echo 'up            - docker compose'
    echo 'down          - docker-compose down for Memseed'
    echo '***************************************'
    echo 'redis         - redis-cli in container'
    echo 'redis db      - available redis databases in container'
    echo 'redis db 3    - connect to 3 redis database in container'
    echo '***************************************'
    echo 'testenv       - Prepare test ENV, no parallel'
    echo 'specs         - prepare parallel, specs in parallel, cucumber in parallel'
    echo 'specs_run     - run only specs in parallel'
    echo 'features_run  - run only features in parallel'
    echo 'staging       - connect to staging'

    echo '**************************************'
    echo 'Future plans:'
    echo 'Use gem for choices??'
    echo 'Print data from .env file through ruby?'
    echo 'After connect to staging cd to project dir and run rails c or tail -f'
fi
